src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandRepository::class)
 */
class Command
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number_order;

    /**
     * @ORM\Column(type="text")
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity=Product::class, inversedBy="commands")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getNumberOrder(): ?string
    {
        return $this->number_order;
    }

    public function setNumberOrder(string $number_order): self
    {
        $this->number_order = $number_order;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        $this->products->removeElement($product);

        return $this;
    }
}

src/Controller/front/BrandController.php
<?php 

namespace App\Controller\front;

use App\Repository\BrandRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class BrandController extends AbstractController
{
    #[Route("/front/brands", name: "BrandList")]
    public function brandsList(BrandRepository $brandRepository)
    {
        $brands = $brandRepository->findAll();
        return $this->render('front/brands.html.twig', ['brands' => $brands]);
    }


    // Système des wildcards {id}
  #[Route("/front/brand/{id}", name: "BrandShow")]
  public function brandShow($id, BrandRepository $brandRepository)
  {

      $brand = $brandRepository->find($id); // find() permet de sélectionner qu'un seul élément
      if(isset($brand)){
          return $this->render('front/brand.html.twig', ['brand' => $brand]);
      }else{
          throw  new NotFoundHttpException("Erreur 404. La page que vous cherchez n'a pas été trouvée");
      }
  }
}

src/Controller/front/CommandController.php
<?php

namespace App\Controller\front;

use App\Repository\CommandRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class CommandController extends AbstractController

{

    #[Route("/front/commands", name: "CommandList")]
    public function commandsList(CommandRepository $commandRepository)
    {
        $commands = $commandRepository->findAll();
        return $this->render('front/commands.html.twig', ['commands' => $commands]);
    }



    // Système des wildcards
    #[Route("/front/command/{id}", name: "CommandShow")]
    public function productShow($id, CommandRepository $commandRepository)
    {

        $command = $commandRepository->find($id);
        if (isset($command)) {
            return $this->render('front/command.html.twig', ['command' => $command]);
        } else {
            throw  new NotFoundHttpException("Erreur 404. La page que vous cherchez n'a pas été trouvée");
        }
    }

}

src/Controller/front/ProductController.php
<?php

namespace App\Controller\front;

use App\Entity\Like;
use App\Repository\LikeRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController

{


    // Créer les deux fonctions qui affichent la liste des produits avec leur nom, prix, type, brand,

    #[Route("/front/products", name: "ProductList")]
    public function productsList(ProductRepository $productRepository)
    {
        $products = $productRepository->findAll();
        return $this->render('front/products.html.twig', ['products' => $products]);
    }



    // Système des wildcards
    #[Route("/front/product/{id}", name: "ProductShow")]
    public function productShow($id, ProductRepository $productRepository)
    {

        $product = $productRepository->find($id);
        if (isset($product)) {
            return $this->render('front/product.html.twig', ['product' => $product]);
        } else {
            throw  new NotFoundHttpException("Erreur 404. La page que vous cherchez n'a pas été trouvée");
        }
    }

    #[Route('/front/search', name: 'front_search')]
    public function frontsearch(ProductRepository $productRepository, Request $request)
    {

        // récupérer les données rentrées dans le formulaire 
        $term = $request->query->get('term');

        $products = $productRepository->searchByTerm($term);

        return $this->render('front/search.html.twig', ['products' => $products]);
    }

    // on créer une fonction qui lorsque l'user clique sur le like d'un pdt cela rajotue ou enleve son like sur le pdt
    #[Route("/front/like/product/{id}", name:"product_like")]
    public function likeProduct($id, ProductRepository $productRepository, EntityManagerInterface $entityManagerInterface, LikeRepository $likeRepository)
    {
        $product = $productRepository->find($id);
        $user = $this->getUser();


        // si l'utilisateur n'est pas connecté
        if(!$user) 
        {
            return $this->json(
                ['code'=> 403,
                'message' => "Vous devez vous connecter"], 403);

        }

        // si l'utilisateur connecté clique sur un pdt déjà liké
        if($product->isLikedByUser($user))
        {
            $like = $likeRepository->findOneBy(
                ['product' => $product, 
                'user' => $user]
            );

            $entityManagerInterface->remove($like);
            $entityManagerInterface->flush();

            return $this->json(
                ['code' => 200,
                'message' => "Le like a été supprimé",
                'likes' => $likeRepository->count( 
                    ['product' => $product]
                )], 200);
        }

        $like = new Like();
        $like->setProduct($product);
        $like->setUser($user);

        $entityManagerInterface->persist($like);
        $entityManagerInterface->flush();

            return $this->json(
                ['code' => 200,
                'message' => "Le like a été enregistré",
                'likes' => $likeRepository->count( 
                    ['product' => $product]
                )], 200);

    }


}

src/Controller/front/TypeController.php
<?php 

namespace App\Controller\front;

use App\Repository\TypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TypeController extends AbstractController
{

    // fichier TypeController.php ne fonctionne pas !! 

    #[Route("/front/hello", name: "hello")]
    public function hello()
    {
        return new Response("Hello World");
    }


    #[Route("/front/types", name: "TypeList")]
    public function typesList(TypeRepository $typeRepository)
    {
        $types = $typeRepository->findAll();
        return $this->render('front/types.html.twig', ['types' => $types]);
    }



    // Système des wildcards
  #[Route("/front/type/{id}", name: "TypeShow")]
  public function typeShow($id, TypeRepository $typeRepository)
  {

      $type = $typeRepository->find($id);
          return $this->render('front/type.html.twig', ['type' => $type]);
  }
} 

src/Controller/front/UserController.php
<?php

namespace App\Controller\front;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{

    #[Route("front/user/insert", name: "insert_user")]
    public function insertUser(
        Request $request,
        EntityManagerInterface $entityManagerInterface,
        UserPasswordHasherInterface $userPasswordHasherInterface
    ) {

        $user = new User();

        $userForm = $this->createForm(UserType::class, $user);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {
            $user->setRoles(["ROLE_USER"]);

            // On récupère le password entré dans le formulaire
            $plainPassword = $userForm->get('password')->getData();
            // On hashe le password pour le sécuriser
            $hashedPassword = $userPasswordHasherInterface->hashPassword($user, $plainPassword);
            $user->setPassword($hashedPassword);

            $entityManagerInterface->persist($user);
            $entityManagerInterface->flush();

            return $this->redirectToRoute("ProductList");
        }

        return $this->render('front/userform.html.twig', ['userForm' => $userForm->createView()]);
    }
}

templates/front/base.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> 

		<title>Document</title>
	</head>
	<body>
		<header>
			<form action="{{ path('front_search') }}" method="get">
				<input type="search" name='term' id="">
				<input type="submit" value="Rechercher">
			</form>
		</header>

		{% block main %}{% endblock %}
        
	</body>
</html>

templates/front/brand.html.twig
{% extends "front/base.html.twig" %}


{% block main %}

<center><div class="fluid">
    <center><h1> {{  brand.name }} </h1></center>
    <center><h2> {{  brand.description }} </h2></center>
    {% for product in brand.products %}
    <center> {{ product.name}} </center>
    {% endfor %}
</div></center>



{% endblock %}

templates/front/brands.html.twig
{% extends "front/base.html.twig" %}


{% block main %}

{{ batman }}

     <h1>Liste des Marques</h1> 

    <div class="container">
        {% for brand in brands %}
            <div class="row">
                    {# path permet de rediriger vers une url grace au nom de la route et des paramètres de cette route si nécessaire #}
                    <center><a href="{{ path('BrandShow', {'id' : brand.id}) }}"><h1> {{  brand.name }} </h1></a></center>
            </div>
        {% endfor %}
    </div>


    {% for gproduct in gproducts.getAll %}
        <h3>{{ gproduct.name }}</h3>
    {% endfor %}

{% endblock %}

templates/front/command.html.twig
{% extends "front/base.html.twig" %}


{% block main %}

<center><div class="fluid">

    <center><h1> {{  command.numberOrder}} </h1></center>
     <center><h1> {{  command.price}} € </h1></center>
    {% for product in command.products %}
    <center> {{ product.name}} </center>
    {% endfor %}
   
</div></center>



{% endblock %}

templates/front/commands.html.twig
{% extends 'front/base.html.twig' %}


{% block main %}

    <h1> Les commandes </h1>

    {% for command in commands %}

    <h2>{{ command.numberOrder }}</h2>

    {% endfor %}

{% endblock %}

templates/front/product.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
<center><div class="fluid">
    <center><h1> {{  product.name }} </h1></center>
    <center><h2> {{  product.description }} </h2></center>
    <center><p> {{  product.type.name }} </p></center>
    <center><p> Marque: {{  product.brand.name }} </p></center>
    <center><p> Prix: {{  product.price }} €</p></center>
    <center><p> Produits en stock: {{  product.stock }} </p></center>
    {% for image in product.media %}
    <center><img src="{{ asset('media/' ~ image.src)}}" alt="{{ image.alt }}">

{% endfor %}
</div></center>



{% endblock %}

templates/front/products.html.twig
{% extends "front/base.html.twig" %}


{% block main %}


	<h1>Liste des Produits</h1>

	<hr>

	<div class="container">
		{% for product in products %}
			<div class="row">
				<article>
					{# path permet de rediriger vers une url grace au nom de la route et des paramètres de cette route si nécessaire #}
					<center>
						<a href="{{ path('ProductShow', {'id' : product.id}) }}">
							<h1>
								{{  product.name }}
							</h1>
						</a>
					</center>
					<center>
						<h2>
							{{  product.type.name }}
						</h2>
					</center>
					<center>
						<p>
							{{ product.brand.name }}
						</p>
					</center>
					<center>
						<p>
							{{ product.price }}
							€
						</p>
					</center>

					<center>
						<a
							href="{{ path("product_like", {'id' : product.id}) }}" class="btn btn-link js-likes">
							{# app.user est la variable qui enregistre le user connecté #}
							{% if app.user and product.isLikedByUser(app.user) %}
								<i class="fas fa-thumbs-up"></i>
								{#icon pouce rempli#}
							{% else %}
								<i class="far fa-thumbs-up"></i>
								{# icon pouce vide#}
							{% endif %}

							<span class="js-likes">{{ product.likes | length }}</span>
							<span class="js-label">J'aime</span>
						</a>
					</center>
				</article>
			</div>
			<hr>
		{% endfor %}
	</div>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

function onClickLike(event){
    event.preventDefault();

    const url = this.href;
    const spanCount = this.querySelector('span.js-likes');
    const icone = this.querySelector('i');

    axios.get(url).then(function (response){
        spanCount.textContent = response.data.likes;

        if(icone.classList.contains('fas')){
            icone.classList.replace('fas', 'far');
        } else{
            icone.classList.replace('far', 'fas');
        }
    }).catch(function(error){
        if(error.response.status == 403)
        {
            window.alert("Connexion requise")
        }else {
            window.alert("une erreur c'est produite");
        }
    });


}

document.querySelectorAll('a.js-likes').forEach(function (link){
    link.addEventListener('click', onClickLike)
})


</script>

{% endblock %}

templates/front/search.html.twig
{% extends 'front/base.html.twig' %}


{% block main %}

    <h1> Les produits qui correspondent à votre recherche :</h1>

    {% for product in products %}

    <h2>{{ product.name }}</h2>

    {% endfor %}

{% endblock %}

templates/front/type.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
<center><div class="fluid">
    <center><h1> {{  type.name }} </h1></center>
    <center><h2> {{  type.description }} </h2></center>
    {% for product in type.products %}
    
    <center> <h4>{{ product.name}} </h4></center> 

    {% endfor %}
    
</div></center>


{% endblock %}

templates/front/types.html.twig
{% extends "front/base.html.twig" %}


{% block main %}

    {{ batman }}

     <h1>Liste des Types de produits</h1> 

    <div class="container">
        {% for type in types %}
            <div class="row">
                <article>
                    {# path permet de rediriger vers une url grace au nom de la route et des paramètres de cette route si nécessaire #}
                    <center><a href="{{ path('TypeShow', {'id' : type.id}) }}"><h1> {{  type.name }} </h1></a></center>
                </article>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/front/userform.html.twig
{% extends "front/base.html.twig" %}

{% block main %}

	{{form(userForm)}}
    
{% endblock %}